[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#1e293b"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
