[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
